/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BanDAO;
import Model.Ban;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;


/**
 *
 * @author NHT_Kurumi
 */
public class jp_BanHang extends javax.swing.JPanel {

    BanDAO banDAO = new BanDAO();
    
    List<Ban> ListBan;
    List<Ban> ban;
    /**
     * Creates new form jpBanHang
     */
    public jp_BanHang() {
        initComponents();
//        this.setSize(1800, 836);
//        jpTaoHoaDon.setSize(1244, 836);
        QuanLyBan();
    }

    
    public void QuanLyBan(){
        ListBan = banDAO.getListBan(0);
        if(ListBan != null){
            jpBan.removeAll();
            //Khởi tạo button
            JButton[] btn = new JButton[ListBan.size()];
            for(int i=0;i<ListBan.size();i++){
                btn[i] = new JButton();
                btn[i].setName(String.valueOf(ListBan.get(i).getMaban()));
                String[] mb = ListBan.get(i).getTenban().split(" ");
                btn[i].setText(mb[1]);
                btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Table.png")));
                btn[i].setBackground(Color.decode("#00FF00"));
                btn[i].setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btn[i].setForeground(new java.awt.Color(51, 51, 51));
                if(ListBan.get(i).getTrangthai().equals("Đang phục vụ")){
                    btn[i].setBackground(Color.decode("#FF0000"));
                }
                if(ListBan.get(i).getTrangthai().equals("Đã đặt trước")){
                    btn[i].setBackground(Color.decode("#FFFF00"));
                }                
                btn[i].setPreferredSize(new Dimension(90, 70));

                btn[i].addMouseListener(new MouseAdapter() {
                        @Override
                        public void mousePressed(MouseEvent e) {
//                            JpGoiMon goimon;
//                            ban = cn.GetBan(Integer.parseInt(e.getComponent().getName()));
//                            if(ban != null){                            
//                                goimon = new jpTaoHoaDon(ban.get(0).GetTrangThai(),ban.get(0).GetTenBan(),ban.get(0).GetMaBan());
//                                jpTaoHoaDon.removeAll();
//                                jpTaoHoaDon.add(goimon);
//                                jpTaoHoaDon.updateUI();
//                            }
                        }                    
                });
                jpBan.add(btn[i]);
                jpBan.updateUI();
            }
        }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpQuanLyBan = new javax.swing.JPanel();
        btBanTrong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btBanTrong1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btBanTrong2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpTaoHoaDon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpBan = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1350, 744));

        jpQuanLyBan.setBackground(new java.awt.Color(255, 255, 255));

        btBanTrong.setBackground(new java.awt.Color(0, 255, 0));
        btBanTrong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bàn trống");

        btBanTrong1.setBackground(new java.awt.Color(255, 255, 0));
        btBanTrong1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Đã đặt trước");

        btBanTrong2.setBackground(new java.awt.Color(255, 0, 0));
        btBanTrong2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Đang phục vụ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QuanLyBan.png"))); // NOI18N

        javax.swing.GroupLayout jpQuanLyBanLayout = new javax.swing.GroupLayout(jpQuanLyBan);
        jpQuanLyBan.setLayout(jpQuanLyBanLayout);
        jpQuanLyBanLayout.setHorizontalGroup(
            jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQuanLyBanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpQuanLyBanLayout.createSequentialGroup()
                        .addComponent(btBanTrong1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpQuanLyBanLayout.createSequentialGroup()
                        .addComponent(btBanTrong2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jpQuanLyBanLayout.createSequentialGroup()
                        .addComponent(btBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jpQuanLyBanLayout.setVerticalGroup(
            jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQuanLyBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpQuanLyBanLayout.createSequentialGroup()
                        .addGroup(jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBanTrong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(jpQuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBanTrong2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );

        jpTaoHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jpTaoHoaDon.setLayout(new java.awt.BorderLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QuanCaPhe.jpg"))); // NOI18N
        jpTaoHoaDon.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jpBan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpQuanLyBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jpTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTaoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jpQuanLyBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBanTrong;
    private javax.swing.JButton btBanTrong1;
    private javax.swing.JButton btBanTrong2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jpBan;
    private javax.swing.JPanel jpQuanLyBan;
    private javax.swing.JPanel jpTaoHoaDon;
    // End of variables declaration//GEN-END:variables
}
